<h1 align="center"> Linear Regression</h1>

## Importing necessary libraries

In [16]:
from sklearn.linear_model import LinearRegression
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

### Task: Train a Linear Regression Model Using a Single Variable

In [10]:
# importing dataset from house_dataset.csv and saving it in df variable

df=pd.read_csv("house_dataset.csv")
# Displying no of rows and columns
df.shape

(1000, 2)

In [11]:
# Printing fews records
df.sample(8)

     Area (sqft)  Price (Lakhs)
471         2936          89.45
898         2629          84.59
957         1688          55.49
132         1305          37.24
653         2949          83.47
122          533          17.45
850         1108          31.79
448         2455          75.74

In [13]:
# Now create a Linear Regression model
model=LinearRegression()
model

LinearRegression()

In [14]:
# fit the dependent and independent variable
model.fit(df[["Area (sqft)"]],df["Price (Lakhs)"])

LinearRegression()

In [17]:
# Now do predict 
model.predict([[1500],[700]])

array([44.93249055, 20.69998894])

In [18]:
model.coef_,model.intercept_

(array([0.03029063]), -0.503449974655723)

## Task: Train a Linear Regression Model Using a Multiple Variable

In [20]:
# importing dataset from house_dataset.csv and saving it in df variable
df=pd.read_csv("house_price_dataset_1000.csv")

# Displying no of rows and columns
df.shape

(1000, 3)

In [21]:
# Printing fews records
df.sample(8)

     Area (sqft)  Price (Lakhs)  Bedrooms
130         2319          94.00         4
661         1123          41.35         2
816         2521          77.61         1
697         2642          79.56         1
677         1858          74.68         3
7           1738          67.01         2
369         2310          93.14         4
708         2469          91.32         3

In [22]:
# Now create a Linear Regression model
model=LinearRegression()
model

LinearRegression()

In [24]:
# fit the dependent and independent variable
model.fit(df[["Area (sqft)","Bedrooms"]],df["Price (Lakhs)"])

LinearRegression()

In [25]:
model.coef_,model.intercept_

(array([0.02973443, 4.92564835]), 0.9659495911392213)

In [26]:
test=pd.DataFrame({
"Area (sqft)":[5000,800,1200],
"Bedrooms":[19,4,7]}
)

In [27]:
model.predict(test)

array([243.22539905,  44.45608392,  71.12679944])